# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 551c733f97228e22357e1974ef73bed18a9fe45bc2d9cc23f96d8f60a079afc2b911cfc84425d8f0364efefe20f19aa203437cf9de3872b3c6e4f7e78f4ad3b2

test:
  secret_key_base: 96cbadfc4c34c5b5ce9fa7dd2346d652a93d62d7f5df3193398e0db2d0117730678d5ebc5ba68293c09e1a6061be8c315dc8b5121fc54cb8a3eaf1742ac40ac5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
